# [START app_yaml]
runtime: nodejs8

handlers:

- url: /favicon\.ico
  static_files: favicon.ico
  upload: /favicon\.ico

- url: /assets
  static_dir: public/assets

- url: /.*
  script: auto

# [END app_yaml]
