version: '3'
networks:
	private:
		driver: overlay
services:
	hub:
		image: selenium/hub:${SELENIUM_VERSION}
	ports:
		- "$SELENIUM_PORT:$SELENIUM_PORT"
	deploy:
		mode: global
	placement:
		constraints:
			- node.role == manager
	environment:
		- GRID_BROWSER_TIMEOUT=60000
		- GRID_TIMEOUT=60000
		- GRID_MAX_SESSION=50
		- GRID_MAX_INSTANCES=3
		- GRID_CLEAN_UP_CYCLE=60000
		- GRID_UNREGISTER_IF_STILL_DOWN_AFTER=180000
		- GRID_NEW_SESSION_WAIT_TIMEOUT=60000
	networks:
		- private
firefox:
	image: selenium/node-firefox:${SELENIUM_VERSION}
	volumes:
		- /dev/urandom:/dev/random
	depends_on:
		- hub
	environment:
		- HUB_PORT_4444_TCP_ADDR=hub
	  - HUB_PORT_4444_TCP_PORT=${SELENIUM_PORT}
	  - NODE_MAX_SESSION=1
	entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME -port 5555" /opt/bin/entry_point.sh'
	ports:
		- "5555:5555"
	deploy:
		replicas: 1
	networks:
		- private

chrome:
	image: selenium/node-chrome:${SELENIUM_VERSION}
	volumes:
		- /dev/urandom:/dev/random
	depends_on:
		- hub
	environment:
		- HUB_PORT_4444_TCP_ADDR=hub
	  - HUB_PORT_4444_TCP_PORT=${SELENIUM_PORT}
	  - NODE_MAX_SESSION=1
	entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME -port 5556" /opt/bin/entry_point.sh'
	ports:
		- "5556:5556"
	deploy:
		replicas: 1
	networks:
		- private
