seleniumhub:
    image: selenium/hub:3.6.0-americium
    ports:
        - 4444:4444

firefoxnode:
    image: selenium/node-firefox:3.6.0-americium
    ports:
        - 5900
    links:
        - seleniumhub:hub

chromenode:
    image: selenium/node-chrome:3.6.0-americium
    #build: 
        #context: ./
        #dockerfile: Dockerfile-chrome
    ports:
        - 5900
    links:
        - seleniumhub:hub
